TanoshiiMoe/AliceEngine

D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene3.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene4.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene4.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/Player.cpp
D2D-AliceEngine/Engine/Component/TransformComponent.cpp
D2D-AliceEngine/Engine/Component/TransformComponent.h
D2D-AliceEngine/Engine/Effect/Prism.cpp
D2D-AliceEngine/Engine/Effect/Prism.h
D2D-AliceEngine/Engine/Math/Transform.h
D2D-AliceEngine/Engine/UI/UIButton.cpp
D2D-AliceEngine/Engine/UI/UIButton.h

현재까지 전체적인 코드 리팩토링 및 문서 추가

---

D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene2.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene3.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Aru.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Aru2.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Bike/LaneController.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Earth.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Example/ScriptExample.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Moon.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Sun.cpp
D2D-AliceEngine/Engine/Component/BoxComponent.cpp
D2D-AliceEngine/Engine/Component/RenderComponent.cpp
D2D-AliceEngine/Engine/Component/RenderComponent.h
D2D-AliceEngine/Engine/Component/SpriteRenderer.cpp
D2D-AliceEngine/Engine/Component/SpriteRenderer.h
D2D-AliceEngine/Engine/Component/TextRenderComponent.cpp
D2D-AliceEngine/Engine/Component/TextRenderComponent.h
D2D-AliceEngine/Engine/Effect/Prism.cpp
D2D-AliceEngine/Engine/Engine.vcxproj
D2D-AliceEngine/Engine/Engine.vcxproj.filters
D2D-AliceEngine/Engine/Helpers/CoordHelper.cpp
D2D-AliceEngine/Engine/Helpers/CoordHelper.h
D2D-AliceEngine/Engine/Helpers/FFmpegHelper.h
D2D-AliceEngine/Engine/Manager/D2DRenderManager.cpp
D2D-AliceEngine/Engine/Manager/D2DRenderManager.h
D2D-AliceEngine/Engine/Manager/UpdateTaskManager.h
D2D-AliceEngine/Engine/Scene/Scene.cpp
D2D-AliceEngine/Engine/System/RenderSystem.cpp

코드 전체적으로 리팩토링 및 UI 관련 기능 추가

---

D2D-AliceEngine/D2D-AliceEngine/Scripts/Player.cpp
D2D-AliceEngine/Engine/Component/Component.cpp
D2D-AliceEngine/Engine/Component/Component.h
D2D-AliceEngine/Engine/Component/RenderComponent.cpp
D2D-AliceEngine/Engine/Component/RenderComponent.h
D2D-AliceEngine/Engine/Experimental/Collision/CollisionDetector.cpp
D2D-AliceEngine/Engine/System/RenderSystem.cpp
D2D-AliceEngine/Engine/UI/UIText.cpp

컴포넌트 Relative Transform 추가

---

D2D-AliceEngine/D2D-AliceEngine/D2D-AliceEngine.vcxproj
D2D-AliceEngine/D2D-AliceEngine/D2D-AliceEngine.vcxproj.filters
D2D-AliceEngine/D2D-AliceEngine/DemoGameApp.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene4.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Bike/BikeMovementScript.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Bike/BikeMovementScript.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/Player.cpp

Bike Movement Scipt

---

D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene2.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene2.h
D2D-AliceEngine/Engine/Scene/Scene.cpp
D2D-AliceEngine/Engine/Scene/Scene.h

Scene FindObject 안전하게 찾기

---

D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene2.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene2.h
D2D-AliceEngine/Engine/Scene/Scene.h

Scene FindObjectName Tag Type 수정

Scene FindObjectName Tag Type 수정

---

D2D-AliceEngine/Engine/Component/TextRenderComponent.cpp
D2D-AliceEngine/Engine/Component/TextRenderComponent.h

텍스트 폰트 변경 기능 추가

---

D2D-AliceEngine/D2D-AliceEngine/DemoGameApp.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Spine2D/SpineScript.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Spine2D/SpineScript.h
D2D-AliceEngine/D2D-AliceEngine/Spine2D/SpineRenderer.cpp
D2D-AliceEngine/Engine/Component/ButtonComponent.cpp
D2D-AliceEngine/Engine/Component/ButtonComponent.h
D2D-AliceEngine/Engine/System/RenderSystem.cpp
D2D-AliceEngine/Engine/System/RenderSystem.h

스파인 2D 유니티 좌표계로 수정, UI Active

---

D2D-AliceEngine/D2D-AliceEngine/Scripts/Aru.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Aru.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/BulletManager.cpp
D2D-AliceEngine/Engine/Core/Input.cpp
D2D-AliceEngine/Engine/Core/Input.h
D2D-AliceEngine/Engine/Manager/TimerManager.cpp
D2D-AliceEngine/Engine/Manager/TimerManager.h

다음처럼 쓰는거 참고. 언리얼 스타일로.
유니티의 Invoke랑 비슷함. 좀더 C++ 스럽게 함수 포인터 날림. 내부코드 참고. 
```c++
TimerManager::Get().SetTimer(Timer, this, &MyObject::SelfDestruct, 5.0f, false);
TimerManager::GetInstance().ClearTimer(timer);
if (TimerManager::Get().IsTimerActive(Timer))
{
OutputDebugStringW(L"타이머가 실행 중입니다\n");
}
TimerManager::Get().PauseTimer(Timer);
TimerManager::Get().UnPauseTimer(Timer);
float elapsed = TimerManager::Get().GetTimerElapsed(Timer);
OutputDebugStringW((L"타이머 경과 시간: " + std::to_wstring(elapsed) + L"\n").c_str());
float remaining = TimerManager::Get().GetTimerRemaining(Timer);
OutputDebugStringW((L"타이머 남은 시간: " + std::to_wstring(remaining) + L"\n").c_str());
```
내부코드.
```c++
template <typename UserClass>
void TimerManager::SetTimer(
FTimerHandle& OutHandle,
UserClass* InObj,
void …
```

언리얼 스타일 타이머 핸들 추가 

---

D2D-AliceEngine/D2D-AliceEngine/DemoGameApp.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/KangScene/KangScene.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/Bullet.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/Bullet.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/BulletManager.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/BulletManager.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/Drone.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/Drone.h
D2D-AliceEngine/Engine/Effect/Prism.cpp
D2D-AliceEngine/Engine/Effect/Prism.h
D2D-AliceEngine/Engine/Manager/TimerManager.cpp

타이머 핸들 TimeScale 연출 추가, 총알 콜리전 추가

타이머 핸들 TimeScale 연출 추가, 총알 콜리전 추가

---

D2D-AliceEngine/D2D-AliceEngine/Scripts/Bike/BikeStatScript.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/Bullet.cpp
D2D-AliceEngine/Engine/Component/TextRenderComponent.h
D2D-AliceEngine/Engine/Experimental/Collision/CollisionDetector.cpp

적 UI 및 체력바, 텍스트 

---

.editorconfig
.gitattributes

인코딩 깨지는거 안깨지게 차단

---

D2D-AliceEngine/Engine/Component/TextRenderComponent.cpp
D2D-AliceEngine/Engine/Component/TextRenderComponent.h
D2D-AliceEngine/Engine/Manager/D2DRenderManager.h

폰트 세팅 안되던 문제 해결

---

D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/BulletManager.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/Widget/TitleWidgetScript.cpp
D2D-AliceEngine/Engine/Component/AudioComponent.cpp
D2D-AliceEngine/Engine/Component/AudioComponent.h
D2D-AliceEngine/Engine/Manager/AudioManager.cpp

fmod 오디오 소리 중간에 안나는 것 오류 해결 1차시도

fmod 오디오 소리 중간에 안나는 것 오류 해결 1차시도

---

D2D-AliceEngine/D2D-AliceEngine/DemoGameApp.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/DemoScene2.cpp
D2D-AliceEngine/Engine/Component/ProgressBarComponent.cpp
D2D-AliceEngine/Engine/Component/ProgressBarComponent.h
D2D-AliceEngine/Engine/Engine.vcxproj
D2D-AliceEngine/Engine/Engine.vcxproj.filters

UI 프로그레스바 컴포넌트 추가

---

D2D-AliceEngine/D2D-AliceEngine/Scripts/Bike/BikeMovementScript.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Bike/BikeMovementScript.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/Player/PlayerManager.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Player/PlayerManager.h

플레이어 점프 완성

---

D2D-AliceEngine/D2D-AliceEngine/D2D-AliceEngine.vcxproj
D2D-AliceEngine/D2D-AliceEngine/D2D-AliceEngine.vcxproj.filters
D2D-AliceEngine/D2D-AliceEngine/DemoGameApp.cpp
D2D-AliceEngine/D2D-AliceEngine/GameManager/EnemyDataManager.cpp
D2D-AliceEngine/D2D-AliceEngine/GameManager/EnemyDataManager.h
D2D-AliceEngine/D2D-AliceEngine/Prefab/Enemy/Core/Car.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/GameScene/Scene_Stage1.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/GameScene/Scene_Stage1.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/Enemy/SpawnerUsingSingleton/EnemySpawnTriggerBox.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Enemy/SpawnerUsingSingleton/EnemySpawnTriggerBox.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/TileMap/TileMapManager.cpp
D2D-AliceEngine/Engine/Object/UObjectBase.cpp
D2D-AliceEngine/Engine/Object/UObjectBase.h
D2D-AliceEngine/Engine/Scene/Scene.cpp
D2D-AliceEngine/Engine/TileMap/TileMapComponent.cpp

적 스폰 에러 해결. 싱글톤으로 데이터 입력. 트리거 박스 생성

적 스폰 에러 해결. 싱글톤으로 데이터 입력. 트리거 박스 생성

---

D2D-AliceEngine/D2D-AliceEngine/Scene/GameScene/Scene_Stage1.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/GameScene/TitleScene.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/SelectScene.cpp
D2D-AliceEngine/Engine/Component/ButtonComponent.cpp
D2D-AliceEngine/Engine/Component/ButtonComponent.h
D2D-AliceEngine/Engine/Core/Input.cpp
D2D-AliceEngine/Engine/Core/Input.h
D2D-AliceEngine/Engine/Manager/SceneManager.cpp
D2D-AliceEngine/Engine/Scene/Scene.cpp
D2D-AliceEngine/Engine/Scene/Scene.h

버튼 스테이트 관련 초기화 에러 해결

---

D2D-AliceEngine/Engine/Define/Define.h
D2D-AliceEngine/Engine/Scene/Scene.cpp

프로그램 세팅 설정

---

D2D-AliceEngine/D2D-AliceEngine/Scripts/Widget/StageWidgetScript.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Widget/StageWidgetScript.h
D2D-AliceEngine/D2D-AliceEngine/Scripts/Widget/TitleWidgetScript.cpp

속도 표기 버그 수정(정수 표기)

---

D2D-AliceEngine/D2D-AliceEngine/GameManager/GamePlayManager.h
D2D-AliceEngine/D2D-AliceEngine/Scene/GameScene/Scene_Stage1.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/GameScene/Scene_Stage2.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/GameScene/Scene_Stage3.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/Drone.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Widget/LocationIndicatorWidgetScript.h

드론 팔 거꾸로 된 것 수정, 마지막 타일 끝 부분 수정

드론 팔 거꾸로 된 것 수정, 마지막 타일 끝 부분 수정

---

D2D-AliceEngine/D2D-AliceEngine/GameManager/GamePlayManager.cpp
D2D-AliceEngine/D2D-AliceEngine/Scene/GameScene/Scene_Stage2.cpp
D2D-AliceEngine/D2D-AliceEngine/Scripts/Weapon/Bullet.cpp
D2D-AliceEngine/Engine/Component/Effect/ParticleComponent.cpp

[fix] null check error

---

D2D-AliceEngine/D2D-AliceEngine/Scripts/Audio/StageAudioScript.cpp

memory타입에서 stream 타입 변경시 버그발생X

[fix] 오디오 사운드재생정지 수정
